version: "3.9"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog_db
    volumes:
      - var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_HOST: db
      DB_NAME: catalog_db
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: